[package]
name = "pihash"
version = "0.1.0"
authors = ["Drew Short <warrick@sothr.com>"]
description = "A simple library for generating perceptual hashes for images and comparing images based on their perceptual hashes."
repository = "https://github.com/warricksothr/Perceptual-Image-Hashing/"
readme = "README.md"
keywords = ["phash", "perceptual", "image", "comparison"]
license = "MIT"
license-file = "LICENSE"

[dependencies]
docopt = "*"
rustc-serialize = "*"
image = "*"
complex = "*"
dft = "*"
sha1 = "*"
